### PR TITLE
Add putRx

### PR DESCRIPTION
**Pull request by hamen**
It's useful to use it with things like `flatMap()` and `Schedulers`.

### CODE REVIEW

**Comment by erickok** [comment]
Thanks for the code! Could you give an example use case?

```
Cheese cheese = ...
Observable.just(RxDatabase.put(cheese)).subscribe();
```

Or when you want the (possibly modified) object:

```
Observable.just(cheese).doOnNext(RxDatabase.put()).subscribe();
```

**Comment by hamen** [comment]
Hi. I'd like to have a chainable syntax. Something like:

```
getNetResponse()
.flatMap(response -> RxDatabase.get(response.id))
.flatMap(dbItem -> doSomething(dbItem))
.flatMap(editedItem -> RxDatabase.put(editedItem))
.subscribe (stored -> Log.d("Successfully stored));
```

What do you think?

**Comment by erickok** [comment]
Good idea, I see how useful this is. I always envisioned doing this through `doOnNext()` like:

```
getNetResponse()
.flatMap(response -> RxDatabase.get(response.id))
.flatMap(dbItem -> doSomething(dbItem))
.doOnNext(editedItem -> RxDatabase.put())
.subscribe (storedItem -> Log.d("Successfully stored));
```

Note that this would give you the item, not the inserted id, but I think that's what you want anyway, no?

I might actually like an Observable better, like your code. However, I would not emit the id but the whole object. Also, which not simply use a build-in construct for that?

```
public <T> Observable<T> putRx(T entity) {
    put(entity);
    return Observable.just(entity);
}
```

**Comment by hamen** [comment]
`doOnNext()` is typically used to explicit some _side-effect_. I'm used to evaluate the result of a storing procedure and move forward accordingly. So I'd go for a `flatMap/concatMap` instead of `doOnNext`.

Your solution will execute the `put()` when the `Observable` is created, not when the `Observer` subscribes. If you want to use `just()`, you should consider using it inside a `defer()`.

**Comment by erickok** [comment]
You are right of course, I wasn't thinking. I like your Observable versions a lot. You are very right about `doOnNext()` being intended for side effects. How about this:

```
public <T> Observable<T> putRx(final T entity) {
    return Observable.defer(new Func0<Observable<T>>() {
        @Override
        public Observable<T> call() {
            put(entity);
            return Observable.just(entity);
        }
    });
}

public <T> Observable<T> deleteRx(final T entity) {
    return Observable.defer(new Func0<Observable<T>>() {
        @Override
        public Observable<T> call() {
            delete(entity);
            return Observable.just(entity);
        }
    });
}
```

This would allow you to do:

```
getNetResponse()
.flatMap(response -> RxDatabase.get(response.id))
.flatMap(dbItem -> doSomething(dbItem))
.flatMap(editedItem -> RxDatabase.put(editedItem))
.doOnNext(putItem -> Log.d("Item added with id " + putItem._id))
.flatMap(putItem -> RxDatabase.delete(editedItem))
.subscribe (removedAgainItem -> Log.d("Successfully stored));
```

(Not very useful to put and delte them again, but you get the idea. :wink:)

**Pull request closed without merging**
